baseURL = 'https://yhmr.github.io/' # デプロイ時に変更してください
languageCode = 'ja'
title = 'yhmr'
theme = "PaperMod"

enableRobotsTXT = true
buildDrafts = false
buildFuture = false
buildExpired = false

[minify]
  disableXML = true
  minifyOutput = true

[params]
  env = "production"
  title = "yhmr"
  description = "Example description"
  keywords = ["Blog", "Portfolio", "PaperMod"]
  author = "Me"
  # images = ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat = "2006年1月2日"
  defaultTheme = "auto" # dark, light
  disableThemeToggle = false

  ShowReadingTime = true
  ShowShareButtons = false
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  # Assets settings
  [params.assets]
    disableHLJS = false # highlight.jsを無効化するか
    # favicon = "<link / abs url>"

  # Profile Mode Settings
  [params.profileMode]
    enabled = true
    title = "yhmr"
    subtitle = "Software Engineer based in Tokyo"
    imageUrl = "https://www.gravatar.com/avatar/affe4c3c7e1f93d05085421a6a42ed75?s=200" # Gravatar
    imageWidth = 120
    imageHeight = 120
    imageTitle = "My Profile"
    buttons = [
        { name = "About", url = "about" },
        { name = "Projects", url = "projects" },
    ]

  # Social Icons
  [[params.socialIcons]]
    name = "github"
    url = "https://github.com/yhmr"
  [[params.socialIcons]]
    name = "twitter"
    url = "https://twitter.com/ksknmnksk"
  [[params.socialIcons]]
    name = "zenn"
    url = "https://zenn.dev/yhmr"

[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 20
